// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// It's a best-practice to keep credentials out of source control. Vite exposes
// environment variables prefixed with `VITE_` via `import.meta.env`.
// These variables can be provided in a local `.env` file or through the
// hosting platform's configuration.

// Cast to `any` to avoid TypeScript complaints in environments where
// the `VITE_` variables are not explicitly typed.
const { VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY } = (import.meta as any).env ?? {};

const SUPABASE_URL: string | undefined = VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY: string | undefined = VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  /*
   * Surface a clear runtime error instead of failing silently when the
   * environment variables are missing. This keeps secrets out of the client
   * bundle and makes mis-configuration obvious during development.
   */
  throw new Error(
    "Supabase credentials are missing. Please define `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY` in your environment."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});